### ISSUE TITLE
The paper mentions three augmentation strategies, but I only found two in the code.

### ISSUE THREAD

**Issue by fishfishfishfishfishfish** [yxonic/DTransformer#6]
The paper mentions three data augmentation strategies: Flip Response, Drop Item, and Swap Adjacent Items. However, I could only find code for Flip Response ：
s_flip[b, i] = 1 - s_flip[b, i]
and Swap Adjacent Items：
q_[b, i], q_[b, i + 1] = q_[b, i + 1], q_[b, i]
s_[b, i], s_[b, i + 1] = s_[b, i + 1], s_[b, i]. 
I couldn't locate code for Drop Item. Can you provide information to help me find the code or provide the core code as in the previous examples?

**Comment by yxonic** [comment]
Drop Item strategy is achieved by applying random mask here. Pos/neg sequences will be assigned different masking to achieve the effect of the contrastive drop operation.

https://github.com/yxonic/DTransformer/blob/479175b295ccad86a59088181d65cea590b6d0a0/DTransformer/model.py#L320-L333

**Comment by fishfishfishfishfishfish** [comment]
Thank you very much!
